Repository TeamOHJO/Frontend, pull requests merged in 2023-12, with the labels that each got.

#105 refact: 토스트팝업 마우스오버 버그 수정
  src/@types/interface.ts
  src/pages/Home/HomeHeart.tsx
  src/pages/Home/HomeHeartToastPopUp.tsx
  src/pages/Home/MenuBar.tsx
Labels: refactor

#112 fix: 인원수 검색 필터링 버그 수정
  src/pages/Home/SearchModal/VisitorSetter.tsx
  src/pages/Home/SearchModal/index.tsx
  src/routes/MainRouter.tsx
Labels: fix

#119 [#108] 팝업 통합 및 fetch > axios로 변경
  .eslintrc.cjs
  .prettierrc.json
  src/@types/interface.ts
  src/api/accommodation.ts
  src/api/index.ts
  src/api/room.ts
  src/components/Heart.tsx
  src/pages/Accommodation/Info/AccommodationInfo.tsx
  src/pages/Accommodation/Info/AccommodationInfoMap.tsx
  src/pages/Accommodation/Info/AccommodationInfoTag.tsx
  src/pages/Accommodation/Info/AccommodationInfoText.tsx
  src/pages/Accommodation/ReservationBtnToastPopup.tsx
  src/pages/Accommodation/Review/AccommodationReview.tsx
  src/pages/Accommodation/Review/AccommodationReviewItem.tsx
  src/pages/Accommodation/Rooms/AccommodationRoomImages.tsx
  src/pages/Accommodation/Rooms/AccommodationRoomItem.tsx
  src/pages/Accommodation/Rooms/AccommodationRoomItemCart.tsx
  src/pages/Accommodation/Rooms/AccommodationRooms.tsx
  src/pages/Accommodation/Rooms/ReservationBtn.tsx
  src/pages/Accommodation/index.tsx
  src/pages/Room/BottomNavi/RoomBottomNavi.tsx
  src/pages/Room/BottomNavi/RoomReservationBtnToastPopup.tsx
  src/pages/Room/Info/RoomInfo.tsx
  src/pages/Room/Info/RoomInfoTag.tsx
  src/pages/Room/Info/RoomInfoText.tsx
  src/pages/Room/RoomSelectedInfo.tsx
  src/pages/Room/index.tsx
Labels: refactor

#120 [#118] 홈페이지 관련 코드 리펙토링/버그수정
  package-lock.json
  package.json
  src/@types/interface.ts
  src/components/Layout/Navigation.tsx
  src/pages/Home/ContentsContainer.tsx
  src/pages/Home/HomeCard.tsx
  src/pages/Home/MenuBar.tsx
  src/states/atom.ts
  src/utils/utils.ts
Labels: refactor

#124 [#121] 홈페이지/마이페이지/로그인 api분리 및 정리
  src/api/home.ts
  src/api/index.ts
  src/api/login.ts
  src/api/mypage.ts
  src/components/Layout/Navigation.tsx
  src/pages/Home/ContentsContainer.tsx
  src/pages/Login/JoinInput.tsx
  src/pages/Login/JoinTabContent.tsx
  src/pages/Login/LoginTabContent.tsx
  src/pages/MyPage/MyPageInfo/InfoInput.tsx
  src/pages/MyPage/MyPageInfo/PasswordSection.tsx
  src/pages/MyPage/MyPageInfo/ResignSection.tsx
  src/pages/MyPage/MyPageInfo/index.tsx
  src/pages/test/Test.tsx
Labels: refactor

#126 [#125] 유저 라우터 적용/recoil-persist 제거
  package-lock.json
  package.json
  src/pages/Home/ContentsContainer.tsx
  src/pages/Home/MenuBar.tsx
  src/pages/Home/SearchModal/index.tsx
  src/pages/Login/index.tsx
  src/routes/MainRouter.tsx
  src/routes/UserRouter.tsx
  src/states/atom.ts
Labels: refactor

#131 [#130] 더보기 스크롤 해결, 불필요한 웹폰트 제거
  index.html
  src/pages/Home/HomeSwiper.tsx
  src/styles/reset.ts
Labels: refactor

#132 refact: 스켈레톤 적용 #129
  index.html
  src/components/Error/index.tsx
  src/pages/Accommodation/AccommodationMainImg.tsx
  src/pages/Accommodation/AccommodationSelect.tsx
  src/pages/Accommodation/AccommodationTitle.tsx
  src/pages/Accommodation/Info/AccommodationInfo.tsx
  src/pages/Accommodation/Info/AccommodationInfoMap.tsx
  src/pages/Accommodation/Info/AccommodationInfoTag.tsx
  src/pages/Accommodation/Info/AccommodationInfoText.tsx
  src/pages/Accommodation/Review/AccommodationReview.tsx
  src/pages/Accommodation/Rooms/AccommodationRooms.tsx
  src/pages/Accommodation/Swiper/OnOpenSwiper.tsx
  src/pages/Accommodation/index.tsx
  src/pages/Room/BottomNavi/RoomBottomNavi.tsx
  src/pages/Room/Info/RoomInfo.tsx
  src/pages/Room/Info/RoomInfoTag.tsx
  src/pages/Room/Info/RoomInfoText.tsx
  src/pages/Room/RoomMainImg.tsx
  src/pages/Room/RoomSelectedInfo.tsx
  src/pages/Room/RoomTitle.tsx
  src/pages/Room/index.tsx
Labels: refactor

#134 docs: 회고 리드미 작성
  README.md
Labels: docs

#136 fix: 리뷰 작성시 토스트팝업 내용없는 버그 수정
  src/pages/AddReview/AddReviewForm.tsx
Labels: fix

#138 [#137] 숙소 이미지 서스펜스/스켈레톤 적용
  src/components/Loading/Skeleton.tsx
  src/pages/Home/HomeCard.tsx
Labels: refactor

#140 [feat] 무한스크롤 구현
  src/hooks/useInfiniteScroll.tsx
  src/pages/Home/ContentsContainer.tsx
Labels: feat
