Repository TeamOHJO/Frontend, pull requests merged in 2023-11, with the labels that each got.

#3 [#1] 라우터 설정
  package-lock.json
  package.json
  src/App.tsx
  src/components/.gitkeep
  src/components/Layout/Navigation.tsx
  src/routes/.gitkeep
  src/routes/MainRouter.tsx
Labels: chore

#4 [#2] UI 라이브러리 설치 & 스타일 테마 설정
  .eslintrc.cjs
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/components/Layout/Navigation.tsx
  src/main.tsx
  src/routes/MainRouter.tsx
  src/styles/.gitkeep
  src/styles/reset.ts
  src/styles/theme.ts
Labels: chore

#9 [#7] 기본 레이아웃 (Outlet + Navigation) 추가
  .eslintrc.cjs
  public/_redirects
  src/App.tsx
  src/components/Layout/Navigation.tsx
  src/routes/MainRouter.tsx
  src/styles/theme.ts
Labels: env, design

#13 [#12] 뱃지 테마 및 사용법 테스트 추가
  src/components/Layout/Footer.tsx
  src/components/Modal/DefaultModal.tsx
  src/components/Modal/ToastPopup.tsx
  src/pages/test/Test.tsx
  src/routes/MainRouter.tsx
  src/styles/chakraTheme.ts
Labels: design

#21 [#15] 메인페이지 레이아웃 추가
  .eslintrc.cjs
  src/@types/interface.ts
  src/components/Layout/Navigation.tsx
  src/components/TopBtn/index.tsx
  src/pages/Home/ContentsContainer.tsx
  src/pages/Home/HomeCard.tsx
  src/pages/Home/HomeHeader.tsx
  src/pages/Home/MenuBar.tsx
  src/pages/Home/SearchBtn.tsx
  src/pages/Home/index.tsx
  src/pages/test/Test.tsx
  src/routes/MainRouter.tsx
  src/styles/theme.ts
Labels: design

#30 [#29] 마이페이지 상단 탭 디자인 및 컴포넌트 생성
  src/pages/MyPage/MyPageInfo.tsx
  src/pages/MyPage/MyPageReservation.tsx
  src/pages/MyPage/MyPageReview.tsx
  src/pages/MyPage/MyPageTabs.tsx
  src/pages/MyPage/index.tsx
  src/routes/MainRouter.tsx
Labels: design

#31 [#18] 리뷰 페이지 레이아웃 제작 및 기능 추가
  package-lock.json
  package.json
  src/components/ReviewCard/NextArrow.tsx
  src/components/ReviewCard/PrevArrow.tsx
  src/components/ReviewCard/ReviewCardBody.tsx
  src/components/ReviewCard/ReviewCardHeader.tsx
  src/components/ReviewCard/ReviewCardImage.tsx
  src/components/ReviewCard/index.tsx
  src/pages/customerReview/ReviewPageTitle.tsx
  src/pages/customerReview/ReviewSubtitle.tsx
  src/pages/customerReview/index.tsx
  src/routes/MainRouter.tsx
Labels: feat, design

#33 [#23] 네비게이션바 디자인
  index.html
  src/components/Layout/Navigation.tsx
  src/components/TopBtn/index.tsx
  src/pages/Basket/index.tsx
  src/pages/Home/HomeCard.tsx
  src/pages/MyPage/index.tsx
  src/pages/WishList/index.tsx
Labels: design

#36 [#35] MyPage 폴더 내부 구조 변경
  src/pages/MyPage/MyPageInfo.tsx
  src/pages/MyPage/MyPageInfo/index.tsx
  src/pages/MyPage/MyPageReservation.tsx
  src/pages/MyPage/MyPageReservation/index.tsx
  src/pages/MyPage/MyPageReview.tsx
  src/pages/MyPage/MyPageReview/index.tsx
  src/pages/MyPage/MyPageSubtitle.tsx
Labels: rename

#37 [#22] 홈페이지 검색 모달 추가
  package-lock.json
  package.json
  src/components/Layout/Navigation.tsx
  src/pages/Home/SearchBtn.tsx
  src/pages/Home/SearchModal/Calendar.tsx
  src/pages/Home/SearchModal/CalendarCustomInput.tsx
  src/pages/Home/SearchModal/RegionSetter.tsx
  src/pages/Home/SearchModal/VisitorSetter.tsx
  src/pages/Home/SearchModal/index.tsx
Labels: design

#42 [#14] 로그인, 회원가입 페이지 레이아웃 및 유효성 검사
  src/@types/interface.ts
  src/components/Layout/Footer.tsx
  src/pages/Login/JoinInput.tsx
  src/pages/Login/JoinTabButton.tsx
  src/pages/Login/JoinTabContent.tsx
  src/pages/Login/LoginInput.tsx
  src/pages/Login/LoginTabButton.tsx
  src/pages/Login/LoginTabContent.tsx
  src/pages/Login/index.tsx
  src/routes/MainRouter.tsx
  src/styles/chakraTheme.ts
  src/utils/utils.ts
Labels: feat, design

#43 [#40] 내 정보관리 초안
  src/pages/MyPage/MyPageInfo/InfoInput.tsx
  src/pages/MyPage/MyPageInfo/index.tsx
Labels: design

#47 [#44] 로그인/회원가입 api 연동
  src/@types/interface.ts
  src/api/index.ts
  src/api/type.ts
  src/components/Modal/ToastPopup.tsx
  src/pages/Login/JoinInput.tsx
  src/pages/Login/JoinTabButton.tsx
  src/pages/Login/JoinTabContent.tsx
  src/pages/Login/LoginInput.tsx
  src/pages/Login/LoginTabButton.tsx
  src/pages/Login/LoginTabContent.tsx
  src/pages/test/Test.tsx
  src/routes/MainRouter.tsx
  src/states/atom.ts
  src/utils/utils.ts
Labels: feat

#50 [#32] 예약(결제) & 완료 페이지 레이아웃 및 부가 기능
  package-lock.json
  package.json
  src/assets/location-outline.svg
  src/components/BookingBtn/index.tsx
  src/components/Layout/ReservationBottomNav.tsx
  src/components/Layout/UnFooterNav.tsx
  src/components/Modal/ReservationModal.tsx
  src/components/ReservationInfo/ReservationBreakDown.tsx
  src/components/ReservationInfo/ReservationDate.tsx
  src/components/ReservationInfo/ReservationInfoCard.tsx
  src/components/ReservationInfo/ReservationPageTitle.tsx
  src/components/ReservationInfo/ReservationSubBreakDown.tsx
  src/components/ReservationInfo/ReservationSubtitle.tsx
  src/components/ReservationInfo/index.tsx
  src/pages/Reservation/ReservationAgreeCard.tsx
  src/pages/Reservation/ReservationAgreeTitle.tsx
  src/pages/Reservation/ReservationPaymentCard.tsx
  src/pages/Reservation/ReservationPaymentTitle.tsx
  src/pages/Reservation/ReservationProdPrice.tsx
  src/pages/Reservation/index.tsx
  src/pages/ReservationComplete/ReservationCompleteText.tsx
  src/pages/ReservationComplete/index.tsx
  src/routes/MainRouter.tsx
Labels: feat, design, docs

#55 [#49] 홈페이지 검색 상태관리 및 네비게이션 보완
  src/components/Layout/Navigation.tsx
  src/components/Loading/index.tsx
  src/pages/Home/SearchModal/index.tsx
  src/routes/MainRouter.tsx
  src/routes/UserRouter.tsx
  src/states/atom.ts
  src/utils/utils.ts
Labels: feat, design

#57 [#54] 객실 상세페이지 세부 디자인
  public/data/roomDetail.json
  src/@types/interface.ts
  src/pages/Room/RoomBottomNavi.tsx
  src/pages/Room/RoomInfo.tsx
  src/pages/Room/RoomInfoText.tsx
  src/pages/Room/RoomMainImg.tsx
  src/pages/Room/RoomNavi.tsx
  src/pages/Room/RoomSelectedInfo.tsx
  src/pages/Room/RoomTitle.tsx
  src/pages/Room/RoomToastPopup.tsx
  src/pages/Room/index.tsx
Labels: feat, design

#59 [#53] 위시리스트 API 제외한 기능 구현
  public/data/wishlist.json
  src/@types/interface.ts
  src/api/index.ts
  src/pages/Basket/BasketDisabledCard.tsx
  src/pages/Basket/BasketTabs.tsx
  src/pages/Basket/index.tsx
  src/pages/WishList/WishListCard.tsx
  src/pages/WishList/index.tsx
  src/states/atom.ts
Labels: feat

#61 [#58] 상세페이지 세부 기능 추가
  public/data/accommodationDetail.json
  src/components/Heart.tsx
  src/pages/Accommodation/AccommodationInfoText.tsx
  src/pages/Accommodation/AccommodationMainImg.tsx
  src/pages/Accommodation/AccommodationRoomImages.tsx
  src/pages/Accommodation/AccommodationRoomItem.tsx
  src/pages/Accommodation/AccommodationRoomItemCart.tsx
  src/pages/Accommodation/AccommodationTitle.tsx
  src/pages/Accommodation/ReservationBtn.tsx
  src/pages/Accommodation/index.tsx
  src/pages/Room/RoomInfo.tsx
Labels: feat, design

#63 [#56] 검색 API 연동, 네비게이션바 활성화
  .eslintrc.cjs
  src/@types/interface.ts
  src/api/index.ts
  src/components/Layout/Navigation.tsx
  src/pages/Home/ContentsContainer.tsx
  src/pages/Home/HomeCard.tsx
  src/pages/Home/MenuBar.tsx
  src/pages/Home/SearchModal/RegionSetter.tsx
  src/pages/Home/SearchModal/index.tsx
  src/pages/Home/index.tsx
  src/pages/Login/LoginTabContent.tsx
  src/pages/WishList/WishListCard.tsx
  src/routes/LoadingRouter.tsx
  src/routes/MainRouter.tsx
  src/states/atom.ts
  src/utils/utils.ts
Labels: feat

#68 fix: 배포오류수정
  src/pages/WishList/WishListCard.tsx
Labels: fix

#69 [#65] 홈(검색)페이지 버그 수정
  package-lock.json
  package.json
  src/api/index.ts
  src/components/Swiper/SwiperComponent.tsx
  src/pages/Home/ContentsContainer.tsx
  src/pages/Home/HomeCard.tsx
  src/pages/Home/MenuBar.tsx
  src/pages/Home/SearchModal/index.tsx
  src/pages/Home/index.tsx
  src/pages/Login/LoginTabContent.tsx
  src/states/atom.ts
  src/utils/utils.ts
Labels: fix

#71 [#62] 상세페이지 API 연동 및 세부 기능 구현
  src/@types/interface.ts
  src/components/Heart.tsx
  src/pages/Accommodation/AccommodationInfoMap.tsx
  src/pages/Accommodation/AccommodationNavi.tsx
  src/pages/Accommodation/AccommodationReview.tsx
  src/pages/Accommodation/AccommodationReviewItem.tsx
  src/pages/Accommodation/AccommodationRoomItem.tsx
  src/pages/Accommodation/AccommodationRoomItemCart.tsx
  src/pages/Accommodation/AccommodationRooms.tsx
  src/pages/Accommodation/AccommodationTitle.tsx
  src/pages/Accommodation/AccommodationToastPopup.tsx
  src/pages/Accommodation/ReservationBtn.tsx
  src/pages/Accommodation/index.tsx
  src/pages/Room/RoomBottomNavi.tsx
  src/pages/Room/RoomInfo.tsx
  src/pages/Room/RoomInfoTag.tsx
  src/pages/Room/RoomNavi.tsx
  src/pages/Room/RoomSelectedInfo.tsx
  src/pages/Room/RoomTitle.tsx
  src/pages/Room/index.tsx
  src/routes/MainRouter.tsx
  src/states/atom.ts
  src/utils/utils.ts
Labels: feat

#74 [#70] review page api 연동 & useReview 훅
  .eslintrc.cjs
  src/@types/interface.ts
  src/api/index.ts
  src/components/Layout/ReservationBottomNav.tsx
  src/components/ReviewCard/ReviewCardBody.tsx
  src/components/ReviewCard/ReviewCardHeader.tsx
  src/components/ReviewCard/ReviewCardImage.tsx
  src/components/ReviewCard/index.tsx
  src/hooks/useReservationData.tsx
  src/hooks/useReviewData.tsx
  src/pages/customerReview/index.tsx
  src/routes/MainRouter.tsx
Labels: feat

#76 [#60] 마이페이지 예약 내역에서 숙박완료된 항목에 대한 리뷰 작성 기능 구현
  .prettierrc.json
  package-lock.json
  package.json
  public/data/reservationData.json
  src/@types/interface.ts
  src/api/index.ts
  src/components/Layout/Navigation.tsx
  src/components/ReviewCard/ReviewCardBody.tsx
  src/components/ReviewCard/ReviewCardHeader.tsx
  src/components/ReviewCard/ReviewCardImage.tsx
  src/components/StarRating/index.tsx
  src/pages/Accommodation/AccommodationMainImg.tsx
  src/pages/Accommodation/AccommodationNavi.tsx
  src/pages/Accommodation/AccommodationReviewItem.tsx
  src/pages/Accommodation/AccommodationRoomItem.tsx
  src/pages/Accommodation/AccommodationRoomItemCart.tsx
  src/pages/Accommodation/AccommodationRooms.tsx
  src/pages/Accommodation/AccommodationSelect.tsx
  src/pages/Accommodation/AccommodationTitle.tsx
  src/pages/Accommodation/AccommodationToastPopup.tsx
  src/pages/Accommodation/ExplanationModal/index.tsx
  src/pages/Accommodation/ReservationBtn.tsx
  src/pages/Accommodation/SelectModal/index.tsx
  src/pages/Accommodation/index.tsx
  src/pages/AddReview/AddReviewForm.tsx
  src/pages/AddReview/AddReviewHeader.tsx
  src/pages/AddReview/AddReviewImages.tsx
  src/pages/AddReview/index.tsx
  src/pages/Basket/BasketFooter.tsx
  src/pages/Home/ContentsContainer.tsx
  src/pages/Home/HomeCard.tsx
  src/pages/Home/SearchModal/index.tsx
  src/pages/Login/LoginTabContent.tsx
  src/pages/MyPage/MyPageReservation/MyPageReservationButtons.tsx
  src/pages/MyPage/MyPageReservation/MyPageReservationCancelled.tsx
  src/pages/MyPage/MyPageReservation/MyPageReservationCard.tsx
  src/pages/MyPage/MyPageReservation/MyPageReservationCompleted.tsx
  src/pages/MyPage/MyPageReservation/MyPageReservationTabs.tsx
  src/pages/MyPage/MyPageReservation/MyPageReservationUpcoming.tsx
  src/pages/MyPage/MyPageReservation/index.tsx
  src/pages/Room/RoomBottomNavi.tsx
  src/pages/Room/RoomInfoTag.tsx
  src/pages/Room/RoomNavi.tsx
  src/pages/Room/RoomSelectedInfo.tsx
  src/pages/Room/RoomTitle.tsx
  src/pages/WishList/WishListCard.tsx
  src/routes/MainRouter.tsx
  src/states/atom.ts
  src/utils/firebase.config.ts
  src/utils/firebase.ts
  src/utils/utils.ts
Labels: feat, design

#80 [#67] 내 정보 관리 기능 추가
  src/api/index.ts
  src/components/HeartToastPopup.tsx
  src/pages/Accommodation/ReservationBtnToastPopup.tsx
  src/pages/MyPage/MyPageInfo/InfoInput.tsx
  src/pages/MyPage/MyPageInfo/PassWordInput.tsx
  src/pages/MyPage/MyPageInfo/PasswordSection.tsx
  src/pages/MyPage/MyPageInfo/index.tsx
  src/pages/Room/RoomReservationBtnToastPopup.tsx
  src/states/atom.ts
Labels: feat

#86 [#79] 상세 페이지 디테일
  src/components/Layout/UnFooterNav.tsx
  src/pages/Accommodation/AccommodationNavi.tsx
  src/pages/Accommodation/AccommodationRoomItem.tsx
  src/pages/Accommodation/index.tsx
  src/pages/Room/RoomBottomNavi.tsx
  src/pages/Room/RoomNavi.tsx
  src/pages/Room/index.tsx
Labels: feat

#87 [#66] 추가 기능 보완 및 버그 수정
  src/components/Layout/Footer.tsx
  src/components/Layout/Navigation.tsx
  src/pages/Home/ContentsContainer.tsx
  src/pages/Home/HomeCard.tsx
  src/pages/Home/HomeHeart.tsx
  src/pages/Home/HomeHeartToastPopUp.tsx
  src/pages/Home/HomeSwiper.tsx
  src/pages/Home/SearchBtn.tsx
  src/pages/Home/SearchModal/Calendar.tsx
  src/pages/Home/SearchModal/index.tsx
  src/routes/MainRouter.tsx
  src/utils/utils.ts
Labels: fix, feat

#91 [#88]DELETE 팝업 추가가
  src/pages/Home/ContentsContainer.tsx
  src/pages/MyPage/MyPageReview/MyReviewToastPopup.tsx
  src/pages/MyPage/MyPageReview/ReviewCard.tsx
  src/pages/MyPage/MyPageReview/index.tsx
Labels: feat

#90 [#75] 예약(결제) 페이지 & 예약(결제)완료 페이지 기능 및 api 연동
  .eslintrc.cjs
  package-lock.json
  src/@types/interface.ts
  src/api/index.ts
  src/api/type.ts
  src/components/BookingBtn/index.tsx
  src/components/Layout/ReservationBottomNav.tsx
  src/components/Modal/ReservationModal.tsx
  src/components/ReservationInfo/ReservationBreakDown.tsx
  src/components/ReservationInfo/ReservationDate.tsx
  src/components/ReservationInfo/ReservationInfoCard.tsx
  src/components/ReservationInfo/ReservationSubBreakDown.tsx
  src/components/ReservationInfo/index.tsx
  src/context/checkboxContext.tsx
  src/hooks/useReservationData.tsx
  src/pages/Reservation/ReservationAgreeTitle.tsx
  src/pages/Reservation/ReservationProdPrice.tsx
  src/pages/Reservation/index.tsx
  src/pages/ReservationComplete/ReservationCompleteText.tsx
  src/pages/ReservationComplete/index.tsx
  src/utils/utils.ts
Labels: fix, feat, design

#96 [#95]회원탈퇴기능 추가
  src/api/index.ts
  src/pages/Login/JoinTabContent.tsx
  src/pages/MyPage/MyPageInfo/PasswordSection.tsx
  src/pages/MyPage/MyPageInfo/ResignSection.tsx
  src/pages/MyPage/MyPageInfo/index.tsx
Labels: feat

#98 [#94] 마이페이지 예약 내역 API 연동 및 버그 수정
  src/@types/interface.ts
  src/api/index.ts
  src/components/ReservationInfo/ReservationBreakDown.tsx
  src/components/ReservationInfo/ReservationInfoCard.tsx
  src/components/ReservationInfo/ReservationSubBreakDown.tsx
  src/components/ReservationInfo/index.tsx
  src/pages/Basket/BasketCard.tsx
  src/pages/Basket/BasketDisabledCard.tsx
  src/pages/Basket/index.tsx
  src/pages/MyPage/MyPageReservation/MyPageReservationCancelled.tsx
  src/pages/MyPage/MyPageReservation/MyPageReservationCard.tsx
  src/pages/MyPage/MyPageReservation/MyPageReservationCompleted.tsx
  src/pages/MyPage/MyPageReservation/MyPageReservationNoHistory.tsx.tsx
  src/pages/MyPage/MyPageReservation/MyPageReservationTabs.tsx
  src/pages/MyPage/MyPageReservation/MyPageReservationUpcoming.tsx
  src/pages/MyPage/MyPageReservation/index.tsx
  src/pages/ReservationComplete/index.tsx
  src/pages/WishList/WishListCard.tsx
  src/pages/WishList/index.tsx
  src/states/atom.ts
  src/styles/chakraTheme.ts
  src/utils/utils.ts
Labels: fix, feat

#99 design: 파비콘 추가
  index.html
  public/OH!.svg
Labels: design

#100 Feat/#99 리뷰 작성 기능 수정
  src/api/index.ts
  src/pages/AddReview/AddReviewForm.tsx
Labels: fix

#101 [#93] conflict error 해결 및 가격 유틸 설정 & location,star api연동
  src/@types/interface.ts
  src/components/BookingBtn/index.tsx
  src/components/Modal/ReservationModal.tsx
  src/components/ReservationInfo/ReservationBreakDown.tsx
  src/components/ReservationInfo/ReservationSubBreakDown.tsx
  src/pages/Reservation/ReservationProdPrice.tsx
  src/pages/Reservation/ReservationToastPopup.tsx
  src/pages/ReservationComplete/index.tsx
  src/utils/utils.ts
Labels: fix
